// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFp8XNz5STS6nkKJM5Z_2fGL9GAZ2u3Pg',
    appId: '1:639841678567:web:63a42e7fc17a1d3f229e42',
    messagingSenderId: '639841678567',
    projectId: 'chat-app-92e6a',
    authDomain: 'chat-app-92e6a.firebaseapp.com',
    storageBucket: 'chat-app-92e6a.firebasestorage.app',
    measurementId: 'G-1RXQ5WVBFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfitc5wZf8vnAVFkRTqYxuuRU4u6guUxo',
    appId: '1:639841678567:android:35ec17d8d4af8343229e42',
    messagingSenderId: '639841678567',
    projectId: 'chat-app-92e6a',
    storageBucket: 'chat-app-92e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI5ilrldA2PkzvDqgSM1w0pAzOkkcoHAA',
    appId: '1:639841678567:ios:6e593ce98e9191a4229e42',
    messagingSenderId: '639841678567',
    projectId: 'chat-app-92e6a',
    storageBucket: 'chat-app-92e6a.firebasestorage.app',
    iosClientId: '639841678567-80rkn72eqthh5ul38drlcf3obfdn2uuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI5ilrldA2PkzvDqgSM1w0pAzOkkcoHAA',
    appId: '1:639841678567:ios:6e593ce98e9191a4229e42',
    messagingSenderId: '639841678567',
    projectId: 'chat-app-92e6a',
    storageBucket: 'chat-app-92e6a.firebasestorage.app',
    iosClientId: '639841678567-80rkn72eqthh5ul38drlcf3obfdn2uuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFp8XNz5STS6nkKJM5Z_2fGL9GAZ2u3Pg',
    appId: '1:639841678567:web:9d82ab3ac9d41066229e42',
    messagingSenderId: '639841678567',
    projectId: 'chat-app-92e6a',
    authDomain: 'chat-app-92e6a.firebaseapp.com',
    storageBucket: 'chat-app-92e6a.firebasestorage.app',
    measurementId: 'G-Q5269FYJZF',
  );

}